# Generated by Django 6.0.3 on 2026-05-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(verbose_name=100)),
                ('password', models.CharField(verbose_name=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='veh_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('van', 'Van'), ('auto', 'Auto'), ('heavy_loader', 'Heavy Loader'), ('others', 'Others')], default='car', max_length=20)),
                ('reg_number', models.CharField(max_length=20)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('rc', models.ImageField(blank=True, null=True, upload_to='rc_images/')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_week', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('fuel', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=10)),
                ('trans', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
