# Generated by Django 6.0.3 on 2026-05-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veh_listing',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='verification_images/'),
        ),
        migrations.AddField(
            model_name='veh_listing',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='verification_images/'),
        ),
    ]
