# Generated by Django 6.0.3 on 2026-05-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_veh_listing_img1_veh_listing_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veh_listing',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='veh_listing',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='veh_listing',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='veh_listing',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='veh_listing',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='veh_listing',
            name='img2',
        ),
    ]
