# Generated by Django 6.0.3 on 2026-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_veh_listing_image1_remove_veh_listing_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veh_listing',
            name='type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('auto', 'Auto')], default='car', max_length=20),
        ),
    ]
