# Generated by Django 6.0.3 on 2026-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_veh_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='veh_listing',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='veh_listing',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='veh_listing',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='veh_listing',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
