# Generated by Django 6.0.3 on 2026-05-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_veh_listing_image1_veh_listing_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veh_listing',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='verification_images/'),
        ),
        migrations.AddField(
            model_name='veh_listing',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='verification_images/'),
        ),
    ]
