# Generated by Django 6.0.3 on 2026-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_veh_listing_img1_veh_listing_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veh_listing',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='verification_images/'),
        ),
        migrations.AlterField(
            model_name='veh_listing',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='verification_images/'),
        ),
    ]
