# Generated by Django 6.0.3 on 2026-05-07 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_veh_listing_img1_alter_veh_listing_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('Aadhar_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=20)),
                ('license_image', models.FileField(blank=True, null=True, upload_to='license_images/')),
                ('aadhar_image', models.FileField(blank=True, null=True, upload_to='aadhar_images/')),
                ('booking_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.veh_listing')),
            ],
        ),
    ]
