# Generated by Django 6.0.3 on 2026-05-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rental_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
