# Generated by Django 6.0.3 on 2026-05-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_booking_rental_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rental_type',
        ),
    ]
