# Generated by Django 6.0.3 on 2026-05-14 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_booking_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='veh_listing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.user'),
        ),
    ]
