# Generated by Django 6.0.3 on 2026-05-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_booking_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner',
            new_name='user',
        ),
    ]
