# Generated by Django 6.0.3 on 2026-06-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_rename_owner_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veh_listing',
            name='price_per_month',
        ),
        migrations.RemoveField(
            model_name='veh_listing',
            name='price_per_week',
        ),
        migrations.RemoveField(
            model_name='veh_listing',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='veh_listing',
            name='reg_number',
        ),
    ]
