# Generated by Django 6.0.3 on 2026-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_remove_veh_listing_price_per_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veh_listing',
            name='type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('auto', 'Auto'), ('heavy vehicle', 'Heavy Vehicle'), ('other', 'Other')], default='car', max_length=20),
        ),
    ]
