# Generated by Django 6.0.3 on 2026-06-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
