# Generated by Django 6.0.3 on 2026-06-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_remove_review_vehicle_remove_user_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
