# Generated by Django 6.0.3 on 2026-06-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_rename_username_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='name',
        ),
    ]
