# Generated by Django 6.0.3 on 2026-06-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_rename_username_login_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='email',
        ),
    ]
