# Generated by Django 6.0.3 on 2026-06-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_rename_name_login_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='name',
        ),
    ]
