# Generated by Django 6.0.6 on 2026-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_remove_contact_subject_contact_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='veh_listing',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
