# Generated by Django 6.0.6 on 2026-07-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
